version: "3.8"
services:
    bkel-mail:
        build: .
        container_name: bkel-mail-c
        image: bkel-mail:v1
        ports:
            - "6969:4001"
        volumes:
            - .:/app
            - /app/node_modules
        env_file: .env
